
INSERT INTO pokemon_habilidadlegendaria (id, nombre, tipo, descripcion) VALUES
(1, 'Presión', 'Pasiva', 'Aumenta el uso de PP del oponente.'),
(2, 'Electrogénesis', 'Activa', 'Crea un campo eléctrico al entrar al combate.'),
(3, 'Llama Solar', 'Pasiva', 'Aumenta el poder de los movimientos de tipo fuego en clima soleado.'),
(4, 'Impasible', 'Pasiva', 'Sube la Velocidad cuando se pone nervioso.'),
(5, 'Sincronía', 'Pasiva', 'Pasa el estado alterado recibido al rival.'),
(6, 'Absorbe Electricidad', 'Pasiva', 'Recupera PS si recibe un ataque eléctrico.'),
(7, 'Cuerpo Ardiente', 'Pasiva', 'Puede quemar al oponente al contacto.'),
(8, 'Velo Agua', 'Pasiva', 'Previene quemaduras.'),
(9, 'Multiescamas', 'Pasiva', 'Reduce el daño recibido si los PS están al máximo.'),
(10, 'Regeneración', 'Pasiva', 'Restaura PS al cambiar de Pokémon.'),
(11, 'Cura Natural', 'Pasiva', 'Cura los problemas de estado al cambiar.'),
(12, 'Robustez', 'Pasiva', 'El Pokémon no se debilita de un golpe.'),
(13, 'Gélido', 'Pasiva', 'Sube el poder de movimientos tipo hielo en clima frío.'),
(14, 'Metal Liviano', 'Pasiva', 'Reduce el peso del Pokémon.'),
(15, 'Vista Lince', 'Pasiva', 'Evita que la precisión se reduzca.'),
(16, 'Contemplación', 'Pasiva', 'Sube la Defensa especial al entrar en combate.'),
(17, 'Intimidación', 'Pasiva', 'Reduce el Ataque del oponente al entrar en combate.'),
(18, 'Sequía', 'Pasiva', 'Crea un clima soleado al entrar al combate.'),
(19, 'Punto Tóxico', 'Pasiva', 'Puede envenenar al rival al contacto.'),
(20, 'Garra Dura', 'Pasiva', 'Aumenta el poder de los movimientos que hacen contacto físico.'),
(21, 'Sistema Alfa', 'Pasiva', 'Cambia el tipo del Pokémon en combate.'),
(22, 'Escudo Magma', 'Pasiva', 'Evita quemaduras.'),
(23, 'Ráfaga Delta', 'Activa', 'Elimina los efectos de las habilidades climáticas.'),
(24, 'Deseo Cura', 'Activa', 'Restaura PS al Pokémon tras algunos turnos.'),
(25, 'Generosidad', 'Pasiva', 'Duplica el efecto de objetos curativos.'),
(26, 'Alma Ardiente', 'Pasiva', 'Sube el poder de movimientos de tipo fuego.'),
(27, 'Presión', 'Pasiva', 'Aumenta el uso de PP del oponente.'),
(28, 'Telepatía', 'Pasiva', 'Evita daño de movimientos aliados en combate doble.'),
(29, 'Aura Oscura', 'Pasiva', 'Refuerza los movimientos de tipo siniestro.'),
(30, 'Cosecha', 'Pasiva', 'Recupera la baya usada tras el turno.'),
(31, 'Llovizna', 'Pasiva', 'Crea lluvia al entrar en combate.'),
(32, 'Mente Férrea', 'Pasiva', 'Evita movimientos de estado enemigos.'),
(33, 'Receptáculo', 'Pasiva', 'Copia la habilidad de un compañero debilitado.'),
(34, 'Velocidad Extrema', 'Activa', 'Aumenta la Velocidad al estar en combate.'),
(35, 'Espejo Mágico', 'Pasiva', 'Refleja movimientos de estado al rival.'),
(36, 'Cuerpo Puro', 'Pasiva', 'Evita que se reduzcan sus estadísticas.'),
(37, 'Aura de Hada', 'Pasiva', 'Fortalece los movimientos de tipo hada.'),
(38, 'Corte Fuerte', 'Pasiva', 'Aumenta la probabilidad de golpes críticos.'),
(39, 'Adaptabilidad', 'Pasiva', 'Fortalece los movimientos que coincidan con el tipo del Pokémon.'),
(40, 'Alma Plateada', 'Pasiva', 'Evita ser debilitado con un solo golpe.'),
(41, 'Sombra Trampa', 'Pasiva', 'Impide que los Pokémon enemigos huyan.'),
(42, 'Escudo Forjado', 'Pasiva', 'Aumenta la defensa en el primer turno del combate.'),
(43, 'Filtro', 'Pasiva', 'Reduce el daño recibido de movimientos supereficaces.'),
(44, 'Guardia Prisma', 'Pasiva', 'Reduce el daño de ataques múltiples.'),
(45, 'Cola Marina', 'Activa', 'Aumenta la potencia de movimientos tipo agua.'),
(46, 'Escamas Multicolor', 'Pasiva', 'Reduce el daño de ataques al máximo de PS.'),
(47, 'Recarga Rápida', 'Pasiva', 'Permite recargar movimientos de dos turnos más rápido.'),
(48, 'Aura Dragón', 'Pasiva', 'Fortalece los movimientos de tipo dragón.'),
(49, 'Dicha Cósmica', 'Pasiva', 'Aumenta la probabilidad de efectos secundarios.'),
(50, 'Fuerza Lunar', 'Pasiva', 'Potencia movimientos tipo hada bajo la luna llena.'),
(51, 'Vínculo Almado', 'Pasiva', 'Aumenta el ataque de Pokémon aliados voladores.'),
(52, 'Escudo Psíquico', 'Pasiva', 'Reduce el daño de ataques tipo psíquico.'),
(53, 'Luz Primigenia', 'Pasiva', 'Genera luz intensa para movimientos de tipo fuego y planta.'),
(54, 'Alma Pura', 'Pasiva', 'Evita cambios de estado.'),
(55, 'Mente Veloz', 'Pasiva', 'Aumenta la velocidad en situaciones de presión.'),
(56, 'Absorbe Sombras', 'Pasiva', 'Recupera PS al recibir ataques tipo fantasma.'),
(57, 'Claridad Serena', 'Pasiva', 'Previene confusión en climas lluviosos.'),
(58, 'Fuerza Terrestre', 'Pasiva', 'Potencia movimientos tipo tierra en climas soleados.'),
(59, 'Adaptador Dimensional', 'Activa', 'Aumenta la evasión en distorsión del espacio-tiempo.'),
(60, 'Aura Gélida', 'Pasiva', 'Fortalece movimientos tipo hielo.'),
(61, 'Firmeza', 'Pasiva', 'Evita ser debilitado en un solo golpe.'),
(62, 'Eco Cósmico', 'Pasiva', 'Duplica movimientos de eco.'),
(63, 'Guardia Escarlata', 'Pasiva', 'Aumenta la defensa en combate con dragones.'),
(64, 'Velo Etéreo', 'Pasiva', 'Reduce daño de ataques de tipo siniestro.'),
(65, 'Generador Prisma', 'Activa', 'Aumenta el ataque en turnos impares.'),
(66, 'Corazón Valiente', 'Pasiva', 'Aumenta la defensa especial frente a dragones.'),
(67, 'Escudo Cromado', 'Pasiva', 'Evita bajadas de defensa y ataque especial.'),
(68, 'Visión Expandida', 'Activa', 'Aumenta precisión en combate doble.'),
(69, 'Colmillo Espiritual', 'Pasiva', 'Aumenta probabilidad de retroceso en ataques de contacto.'),
(70, 'Fuerza Motriz', 'Pasiva', 'Aumenta ataque en climas eléctricos.'),
(71, 'Espíritu Unido', 'Pasiva', 'Aumenta el ataque especial cuando hay aliados debilitados.'),
(72, 'Aura de Gravedad', 'Pasiva', 'Potencia movimientos de contacto físico en la gravedad.'),
(73, 'Velocidad Prismática', 'Activa', 'Duplica velocidad en distorsión espacio-temporal.'),
(74, 'Héroe Justiciero', 'Pasiva', 'Aumenta la defensa en combate con siniestros.'),
(75, 'Potencia Legendaria', 'Activa', 'Aumenta el ataque en los primeros turnos de combate.');