-- Inserción de habilidades legendarias para los 73 Pokémon
INSERT INTO pokemon_habilidadlegendaria (nombre, tipo, descripcion, pokemon_id) VALUES
('Tormenta Glacial', 'Hielo', 'Congela todo a su paso con una tormenta gélida.', 1),
('Impacto Trueno', 'Eléctrico', 'Un poderoso ataque eléctrico que genera tormentas.', 2),
('Llamas Eternas', 'Fuego', 'Invoca un fuego eterno que quema todo.', 3),
('Control Psíquico', 'Psíquico', 'Manipula la mente de su oponente con facilidad.', 4),
('Poder Ancestral', 'Psíquico', 'Un poder oculto que puede copiar cualquier habilidad.', 5),
('Rayo Estático', 'Eléctrico', 'Genera descargas eléctricas masivas.', 6),
('Volcán Furioso', 'Fuego', 'Controla erupciones volcánicas.', 7),
('Agua Pura', 'Agua', 'Purifica toda el agua en su entorno.', 8),
('Guardián de los Mares', 'Psíquico', 'Protege los mares con su energía.', 9),
('Fénix Sagrado', 'Fuego', 'Renace de sus cenizas y concede felicidad eterna.', 10),
('Tiempo Ancestral', 'Psíquico', 'Puede viajar en el tiempo y curar heridas.', 11),
('Roca Indestructible', 'Roca', 'Posee una defensa impenetrable.', 12),
('Hielo Eterno', 'Hielo', 'Controla el frío absoluto.', 13),
('Metal Milenario', 'Acero', 'Un cuerpo hecho de metal antiguo e indestructible.', 14),
('Corazón Puro', 'Dragón', 'Protege con un corazón lleno de bondad.', 15),
('Defensor Absoluto', 'Dragón', 'Protege a los débiles a cualquier costo.', 16),
('Mareas Eternas', 'Agua', 'Controla los océanos con su inmenso poder.', 17),
('Poder Terrestre', 'Tierra', 'Crea continentes con su fuerza.', 18),
('Vientos Celestiales', 'Dragón', 'Calma tormentas y conflictos.', 19),
('Milagro Celestial', 'Acero', 'Concede deseos cada mil años.', 20),
('ADN Alienígena', 'Psíquico', 'Un ser alienígena con múltiples formas.', 21),
('Llama Magmática', 'Fuego', 'Controla magma con gran precisión.', 22),
('Líder Legendario', 'Normal', 'El líder supremo de los Regis.', 23),
('Sombra Distorsión', 'Fantasma', 'Habita en el mundo distorsión.', 24),
('Sueños Felices', 'Psíquico', 'Trae felicidad a través de los sueños.', 25),
('Pesadilla Oscura', 'Siniestro', 'Induce pesadillas profundas.', 26),
('Creador del Universo', 'Normal', 'El creador del mundo Pokémon.', 27),
('Victoria Absoluta', 'Psíquico', 'Otorga suerte y éxito garantizado.', 28),
('Rayo Negro', 'Eléctrico', 'Un rayo que desata una tormenta eléctrica.', 29),
('Llama Blanca', 'Fuego', 'Fuego puro que puede derretir cualquier cosa.', 30),
('Hielo del Abismo', 'Hielo', 'Una energía gélida que congela el tiempo.', 31),
('Energía Vital', 'Hada', 'Otorga vida y energía al entorno.', 32),
('Ala Destructora', 'Siniestro', 'Sus alas generan caos y destrucción.', 33),
('Guardián del Orden', 'Dragón', 'Protege el equilibrio del mundo.', 34),
('Sol Radiante', 'Psíquico', 'Ilumina y calienta con el poder del sol.', 35),
('Luz Lunar', 'Psíquico', 'Usa el poder de la luna para restaurar energía.', 36),
('Absorción de Luz', 'Psíquico', 'Controla la luz del universo a voluntad.', 37),
('Energía Cósmica', 'Psíquico', 'Contiene energía cósmica ilimitada.', 38),
('Forma Perfecta', 'Psíquico', 'Un estado de evolución máximo.', 39),
('Forja de Vida', 'Acero', 'Puede dar vida a objetos inanimados.', 40),
('Sombra de la Noche', 'Lucha', 'Habita en las sombras y ataca con sigilo.', 41),
('Metal Líquido', 'Acero', 'Un cuerpo de metal líquido que cambia de forma.', 42),
('Fuerza de Acero', 'Acero', 'Un golpe de acero con poder destructivo.', 43),
('Portal Dimensional', 'Psíquico', 'Controla portales entre dimensiones.', 44),
('Diamante Puro', 'Roca', 'Crea diamantes a partir de la energía.', 45),
('Fusión Elemental', 'Fuego', 'Une fuego y agua en un ataque combinado.', 46),
('Cañón Tecnológico', 'Bicho', 'Un arma creada con alta tecnología.', 47),
('Espíritu Valiente', 'Agua', 'Un espíritu que representa valentía pura.', 48),
('Furia de la Tormenta', 'Eléctrico', 'Desata tormentas eléctricas masivas.', 49),
('Huracán Devastador', 'Volador', 'Crea vientos que arrasan con todo.', 50),
('Bendición de la Tierra', 'Tierra', 'Mejora la fertilidad del suelo.', 51),
('Espada de Acero', 'Acero', 'Un ataque preciso y devastador.', 52),
('Golpe de Roca', 'Roca', 'Destruye cualquier barrera con su fuerza.', 53),
('Defensor del Bosque', 'Planta', 'Protege la naturaleza con su fuerza.', 54),
('Voluntad Pura', 'Psíquico', 'Representa la fuerza de la voluntad.', 55),
('Conocimiento Absoluto', 'Psíquico', 'Otorga sabiduría infinita.', 56),
('Emoción Divina', 'Psíquico', 'Conecta con las emociones de todos.', 57),
('Maestro del Tiempo', 'Acero', 'Controla el flujo del tiempo.', 58),
('Señor del Espacio', 'Agua', 'Rige el espacio y las dimensiones.', 59),
('Habitante del Mar', 'Agua', 'Un protector natural de los océanos.', 60),
('Vínculo Ancestral', 'Agua', 'Forma vínculos profundos con otros.', 61),
('Embajador de la Naturaleza', 'Planta', 'Representa la pureza de la naturaleza.', 62),
('Gratitud Eterna', 'Planta', 'Conecta con el cielo y la gratitud.', 63),
('Canto Inspirador', 'Normal', 'Un canto que inspira a todos.', 64),
('Danza Poderosa', 'Normal', 'Combina ritmo y fuerza en combate.', 65),
('Dimensión Oscura', 'Siniestro', 'Controla dimensiones oscuras.', 66),
('Código Perfecto', 'Normal', 'Un diseño que mejora todas sus habilidades.', 67),
('Evolución Total', 'Tipo variable', 'Cambia para adaptarse a cualquier situación.', 68),
('Guardia Eléctrica', 'Eléctrico', 'Protege con una barrera de electricidad.', 69),
('Rayo Lunar', 'Psíquico', 'Usa energía lunar para atacar.', 70),
('Raíces Sagradas', 'Planta', 'Protege el bosque con su poder.', 71),
('Olas Eternas', 'Agua', 'Un control absoluto de los océanos.', 72),
('Electricidad Salvaje', 'Eléctrico', 'Desata rayos que iluminan el cielo.', 73);
 