INSERT INTO pokemon_pokemonlegendario (nombre, tipo_1, tipo_2, generacion, descripcion, imagen) VALUES
('Articuno', 'Hielo', 'Volador', 1, 'Congela todo con un simple aleteo.', 'Articuno.png'),
('Zapdos', 'Eléctrico', 'Volador', 1, 'Controla rayos y tormentas.', 'Zapdos.png'),
('Moltres', 'Fuego', 'Volador', 1, 'Un Pokémon legendario que controla el fuego.', 'Moltres.png'),
('Mewtwo', 'Psíquico', NULL, 1, 'Creado por manipulación genética.', 'Mewtwo.png'),
('Mew', 'Psíquico', NULL, 1, 'Un Pokémon mítico con habilidades extraordinarias.', 'Mew.png'),
('Raikou', 'Eléctrico', NULL, 2, 'Representa los rayos de las tormentas.', 'Raikou.png'),
('Entei', 'Fuego', NULL, 2, 'Encarnación del fuego volcánico.', 'Entei.png'),
('Suicune', 'Agua', NULL, 2, 'Purifica el agua contaminada.', 'Suicune.png'),
('Lugia', 'Psíquico', 'Volador', 2, 'Guardián de los mares.', 'Lugia.png'),
('Ho-Oh', 'Fuego', 'Volador', 2, 'Concede felicidad eterna.', 'Ho-Oh.png'),
('Celebi', 'Psíquico', 'Planta', 2, 'Viajero del tiempo.', 'Celebi.png'),
('Regirock', 'Roca', NULL, 3, 'Formado de rocas antiguas.', 'Regirock.png'),
('Regice', 'Hielo', NULL, 3, 'Creado en la era glacial.', 'Regice.png'),
('Registeel', 'Acero', NULL, 3, 'Fabricado con metales de hace milenios.', 'Registeel.png'),
('Latias', 'Dragón', 'Psíquico', 3, 'Tiene un corazón bondadoso.', 'Latias.png'),
('Latios', 'Dragón', 'Psíquico', 3, 'Protege a los suyos con su vida.', 'Latios.png'),
('Kyogre', 'Agua', NULL, 3, 'Creador de los mares.', 'Kyogre.png'),
('Groudon', 'Tierra', NULL, 3, 'Creador de los continentes.', 'Groudon.png'),
('Rayquaza', 'Dragón', 'Volador', 3, 'Pacifica a Kyogre y Groudon.', 'Rayquaza.png'),
('Jirachi', 'Acero', 'Psíquico', 3, 'Concede deseos cada mil años.', 'Jirachi.png'),
('Deoxys', 'Psíquico', NULL, 3, 'ADN alienígena con múltiples formas.', 'Deoxys.png'),
('Heatran', 'Fuego', 'Acero', 4, 'Vive en volcanes y controla el magma.', 'Heatran.png'),
('Regigigas', 'Normal', NULL, 4, 'Dirigente de los Regis legendarios.', 'Regigigas.png'),
('Giratina', 'Fantasma', 'Dragón', 4, 'Habita en el mundo distorsión.', 'Giratina.png'),
('Cresselia', 'Psíquico', NULL, 4, 'Trae sueños felices a la gente.', 'Cresselia.png'),
('Darkrai', 'Siniestro', NULL, 4, 'Induce pesadillas.', 'Darkrai.png'),
('Arceus', 'Normal', NULL, 4, 'Creador del universo Pokémon.', 'Arceus.png'),
('Victini', 'Psíquico', 'Fuego', 5, 'Aporta victoria a quien lo posea.', 'Victini.png'),
('Zekrom', 'Dragón', 'Eléctrico', 5, 'Encarnación del trueno.', 'Zekrom.png'),
('Reshiram', 'Dragón', 'Fuego', 5, 'Encarnación del fuego.', 'Reshiram.png'),
('Kyurem', 'Dragón', 'Hielo', 5, 'Es la esencia del frío absoluto.', 'Kyurem.png'),
('Xerneas', 'Hada', NULL, 6, 'Embajador de la vida eterna.', 'Xerneas.png'),
('Yveltal', 'Siniestro', 'Volador', 6, 'Representa la destrucción.', 'Yveltal.png'),
('Zygarde', 'Dragón', 'Tierra', 6, 'Equilibra el orden del mundo.', 'Zygarde.png'),
('Solgaleo', 'Psíquico', 'Acero', 7, 'Representa el sol radiante.', 'Solgaleo.png'),
('Lunala', 'Psíquico', 'Fantasma', 7, 'Representa la luna llena.', 'Lunala.png'),
('Necrozma', 'Psíquico', NULL, 7, 'Controla la luz del universo.', 'Necrozma.png'),
('Cosmog', 'Psíquico', NULL, 7, 'Una estrella bebé con energía cósmica.', 'Cosmog.png'),
('Cosmoem', 'Psíquico', NULL, 7, 'Un Pokémon misterioso, pre-evolución.', 'Cosmoem.png'),
('Magearna', 'Acero', 'Hada', 7, 'Un Pokémon artificial creado hace 500 años.', 'Magearna.png'),
('Marshadow', 'Lucha', 'Fantasma', 7, 'Habita en las sombras.', 'Marshadow.png'),
('Meltan', 'Acero', NULL, 7, 'Un Pokémon compuesto por metal líquido.', 'Meltan.png'),
('Melmetal', 'Acero', NULL, 7, 'Evolución de Meltan con gran poder físico.', 'Melmetal.png'),
('Hoopa', 'Psíquico', 'Fantasma', 6, 'Un Pokémon que puede controlar dimensiones.', 'Hoopa.png'),
('Diancie', 'Roca', 'Hada', 6, 'Un Pokémon que crea diamantes a voluntad.', 'Diancie.png'),
('Volcanion', 'Fuego', 'Agua', 6, 'Controla fuego y agua simultáneamente.', 'Volcanion.png'),
('Genesect', 'Bicho', 'Acero', 5, 'Un Pokémon revivido y mejorado con tecnología.', 'Genesect.png'),
('Keldeo', 'Agua', 'Lucha', 5, 'Un Pokémon místico conocido por su valentía.', 'Keldeo.png'),
('Thundurus', 'Eléctrico', 'Volador', 5, 'Un guardián de las tormentas eléctricas.', 'Thundurus.png'),
('Tornadus', 'Volador', NULL, 5, 'Controla los vientos huracanados.', 'Tornadus.png'),
('Landorus', 'Tierra', 'Volador', 5, 'Crea fertilidad en los campos.', 'Landorus.png'),
('Cobalion', 'Acero', 'Lucha', 5, 'Líder del trío de espadas legendarias.', 'Cobalion.png'),
('Terrakion', 'Roca', 'Lucha', 5, 'Protege a los débiles con gran fuerza.', 'Terrakion.png'),
('Virizion', 'Planta', 'Lucha', 5, 'Un defensor de los bosques y la naturaleza.', 'Virizion.png'),
('Azelf', 'Psíquico', NULL, 4, 'Representa la voluntad en el mundo Pokémon.', 'Azelf.png'),
('Uxie', 'Psíquico', NULL, 4, 'El guardián del conocimiento.', 'Uxie.png'),
('Mesprit', 'Psíquico', NULL, 4, 'Personifica las emociones humanas.', 'Mesprit.png'),
('Dialga', 'Acero', 'Dragón', 4, 'Controla el tiempo y las dimensiones.', 'Dialga.png'),
('Palkia', 'Agua', 'Dragón', 4, 'Rige el espacio y las dimensiones.', 'Palkia.png'),
('Phione', 'Agua', NULL, 4, 'Habita en los mares y ríos.', 'Phione.png'),
('Manaphy', 'Agua', NULL, 4, 'Tiene un vínculo especial con Phione.', 'Manaphy.png'),
('Shaymin (Forma Tierra)', 'Planta', NULL, 4, 'Embajador de la naturaleza.', 'Shaymin_Tierra.png'),
('Shaymin (Forma Cielo)', 'Planta', 'Volador', 4, 'Representa la gratitud y el cielo.', 'Shaymin_Cielo.png'),
('Meloetta (Forma Lírica)', 'Normal', 'Psíquico', 5, 'Un Pokémon musical que inspira emociones.', 'Meloetta_Lirica.png'),
('Meloetta (Forma Danza)', 'Normal', 'Lucha', 5, 'Un Pokémon que combina música y fuerza.', 'Meloetta_Danza.png'),
('Hoopa (Forma Desatada)', 'Psíquico', 'Siniestro', 6, 'Un Pokémon legendario que controla dimensiones.', 'Hoopa_Desatada.png'),
('Código Cero', 'Normal', NULL, 7, 'Un Pokémon creado artificialmente.', 'Codigo_Cero.png'),
('Silvally', 'Tipo variable', NULL, 7, 'La evolución de Código Cero.', 'Silvally.png'),
('Tapu Koko', 'Eléctrico', 'Hada', 7, 'Guardián de la isla Melemele.', 'Tapu_Koko.png'),
('Tapu Lele', 'Psíquico', 'Hada', 7, 'Guardián de la isla Akala.', 'Tapu_Lele.png'),
('Tapu Bulu', 'Planta', 'Hada', 7, 'Guardián de la isla Ula-Ula.', 'Tapu_Bulu.png'),
('Tapu Fini', 'Agua', 'Hada', 7, 'Guardián de la isla Poni.', 'Tapu_Fini.png'),
('Zeraora', 'Eléctrico', NULL, 7, 'Un Pokémon místico que controla electricidad.', 'Zeraora.png');
