# Generated by Django 5.1.1 on 2024-12-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadLegendaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonLegendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_1', models.CharField(choices=[('agua', 'Agua'), ('fuego', 'Fuego'), ('planta', 'Planta'), ('eléctrico', 'Eléctrico'), ('psíquico', 'Psíquico')], max_length=20)),
                ('tipo_2', models.CharField(blank=True, choices=[('agua', 'Agua'), ('fuego', 'Fuego'), ('planta', 'Planta'), ('eléctrico', 'Eléctrico'), ('psíquico', 'Psíquico')], max_length=20, null=True)),
                ('generación', models.CharField(max_length=50)),
                ('estadísticas', models.JSONField()),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('visitante', 'Visitante')], default='visitante', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventoLegendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=200)),
                ('descripción', models.TextField()),
                ('fecha', models.DateField()),
                ('pokémon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='legendarios.pokemonlegendario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='legendarios.usuario')),
            ],
        ),
    ]
