# Generated by Django 5.1.1 on 2024-12-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=190, unique=True),
        ),
    ]
