# Generated by Django 5.1.1 on 2024-12-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonlegendario',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemonlegendario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
